#!/bin/bash

set -exuo pipefail

tmpdir=$(mktemp -d)
cd "$tmpdir"
mkdir mjs

cp /build/pow_runner.com pow.com
cp /pow/lib.*.mjs mjs/
cp /pow/pow.*.mjs mjs/
cp /pow/pow.mjs mjs/

(
  cd mjs/
  zip ../pow.com *.mjs
)

mkdir -p /dist/macos
cp pow.com pow-macos
echo "o=pow-macos ; " $(head pow.com | grep -a ^dd) | bash
mv -b pow-macos /dist/macos/pow

mkdir -p /dist/linux
cp pow.com pow-linux
sed s/MZqFpD/Ue6OCi/g -i pow-linux
timeout -s9 1 ./pow-linux 1>/dev/null 2>/dev/null || true
mv -b pow-linux /dist/linux/pow

mkdir -p /dist/windows
cp /build/pow.exe /dist/windows/pow.exe
# For windows build we need to distribute the JS files as well
rm -f /dist/windows/*.mjs
cp mjs/*.mjs /dist/windows/

if [ -e /dist/gitmodules/pow-dist-darwin/pow ]; then
  cp /dist/macos/pow /dist/gitmodules/pow-dist-darwin/
fi

if [ -e /dist/gitmodules/pow-dist-linux/pow ]; then
  cp /dist/linux/pow /dist/gitmodules/pow-dist-linux/
fi

if [ -e /dist/gitmodules/pow-windows/pow.exe ]; then
  cp /dist/windows/pow.exe /dist/gitmodules/pow-windows/
  rm -f /dist/gitmodules/pow-windows/*.mjs
  cp mjs/*.mjs /dist/gitmodules/pow-windows/
fi
