#!/bin/bash

set -euo pipefail

if [ "$#" -ne 1 ]; then
  echo "Usage:
    $0 /target/file.exe" 1>&2
  exit 1
fi

file="$1"

cd /build/windows/quickjs/
make -j6 \
  CONFIG_WIN32=y \
  LDEXPORT="-static -s -pthread" \
  EXTRA_LIBS="-lreproc -lws2_32" \
  qjs.exe

cp qjs.exe "$file"
