#!/bin/bash

set -exuo pipefail

tmpdir=$(mktemp -d)
cd "$tmpdir"

cp /pow/lib.*.mjs .
cp /pow/pow.*.mjs .
cp /pow/pow.mjs .
cp /pow/pow.py .
cp /build/pow_runner.com pow.com

zip pow.com lib.*.mjs
zip pow.com pow.*.mjs
zip pow.com pow.mjs
zip pow.com pow.py

mkdir -p /dist/macos
cp pow.com pow-macos
echo "o=pow-macos ; " $(head pow.com | grep -a ^dd) | bash
mv -b pow-macos /dist/macos/pow

mkdir -p /dist/linux
cp pow.com pow-linux
sed s/MZqFpD/Ue6OCi/g -i pow-linux
timeout -s9 1 ./pow-linux 1>/dev/null 2>/dev/null || true
mv -b pow-linux /dist/linux/pow

mkdir -p /dist/windows
mv -b pow.com /dist/windows/pow.exe
