#!/bin/bash

set -euo pipefail

type=""
file=""

# https://justine.lol/cosmopolitan/howfat.html

S_Linux=1
S_FreeBSD=32
S_OpenBSD=16
S_NetBSD=64
S_MacOS=8
S_BareMetal=2
S_Windows=4

if [ "$#" -ge 2 ]; then
  type="$1"  # windows or linux-macos
  file="$2"
fi

if [ "$type" = linux-macos ]; then

  SUPPORT_VECTOR=$((S_Linux+S_MacOS))

elif [ "$type" = windows ]; then

  SUPPORT_VECTOR=$((S_Linux+S_Windows))

else

  echo "Usage:
    $0 linux-macos /target/file.sh
    $0 windows /target/file.exe" 1>&2
  exit 1

fi

source /bin/demzify_funcs.sh

make_qjs() {
  make -j6 MODE=tiny CPPFLAGS=-DSUPPORT_VECTOR="$SUPPORT_VECTOR" \
    o/tiny/third_party/quickjs/qjs.com
}

cd /build/cosmopolitan/

if need_demzify; then
  for i in {1..5}; do
    demzify $i
    make_qjs || true
    if ! has_mz_files; then
      break
    fi
  done
fi

make_qjs
cp o/tiny/third_party/quickjs/qjs.com "$file"
rm -rf o/tiny/
