#!/bin/bash

set -euo pipefail

BOOST_VERSION=1.79.0
BOOST_DIRNAME=boost_1_79_0
BOOST_URL=https://boostorg.jfrog.io/artifactory/main/release/${BOOST_VERSION}/source/${BOOST_DIRNAME}.tar.bz2

mkdir -p /build/windows/
cd /build/windows/
wget --no-verbose "$BOOST_URL"
tar -xjf "$BOOST_DIRNAME".tar.bz2
mv "$BOOST_DIRNAME" boost

echo "using gcc : w64 : x86_64-w64-mingw32-g++ ; " > ~/user-config.jam

cd /build/windows/boost/
./bootstrap.sh --with-libraries=filesystem --prefix=/usr/x86_64-w64-mingw32
./b2 toolset=gcc-w64 link=static install
