#!/bin/bash

set -euo pipefail

target=/build/windows/quickjs/qjs.c

sed 's/^int main(/int orig_main(/' -i "$target" \
    && cat "$1" >> "$target"

target=/build/cosmopolitan/third_party/quickjs/qjs.c

sed 's/^int main(/int orig_main(/' -i "$target" \
    && cat "$1" >> "$target"
